title: JonnyIsBoss
description: >- # this means to ignore newlines until "baseurl:"
  Beginning
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://shirajuki.github.io" # the base hostname & protocol for your site, e.g. http://shirajuki.github.io
github_username:  shirajuki

collections:
  posts:
    output: true
    layout: post
    permalink: /:categories/:title:output_ext
